/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = {
	light: {
		background: "hsl(0, 0%, 100%)",
		foreground: "hsl(0, 0%, 14.50%)",
		card: "hsl(0, 0%, 100%)",
		cardForeground: "hsl(0, 0%, 14.50%)",
		popover: "hsl(0, 0%, 100%)",
		popoverForeground: "hsl(0, 0%, 14.50%)",
		primary: "hsl(0, 0%, 20.50%)",
		primaryForeground: "hsl(0, 0%, 98.50%)",
		secondary: "hsl(0, 0%, 97%)",
		secondaryForeground: "hsl(0, 0%, 20.50%)",
		muted: "hsl(0, 0%, 97%)",
		mutedForeground: "hsl(0, 0%, 55.60%)",
		accent: "hsl(0, 0%, 97%)",
		accentForeground: "hsl(0, 0%, 20.50%)",
		destructive: "hsl(0, 80%, 57.70%)",
		destructiveForeground: "hsl(0, 0%, 100%)",
		border: "hsl(0, 0%, 92.20%)",
		input: "hsl(0, 0%, 92.20%)",
		ring: "hsl(0, 0%, 70.80%)",
	},
	dark: {
		background: "hsl(240, 10%, 3.90%)",
		foreground: "hsl(0, 0%, 98%)",
		card: "hsl(240, 10%, 3.90%)",
		cardForeground: "hsl(0, 0%, 98%)",
		popover: "hsl(240, 10%, 3.90%)",
		popoverForeground: "hsl(0, 0%, 98%)",
		primary: "hsl(0, 0%, 98%)",
		primaryForeground: "hsl(240, 5.90%, 10%)",
		secondary: "hsl(240, 3.70%, 15.90%)",
		secondaryForeground: "hsl(0, 0%, 98%)",
		muted: "hsl(240, 3.70%, 15.90%)",
		mutedForeground: "hsl(240, 5%, 64.90%)",
		accent: "hsl(240, 3.70%, 15.90%)",
		accentForeground: "hsl(0, 0%, 98%)",
		destructive: "hsl(0, 62.80%, 30.60%)",
		destructiveForeground: "hsl(0, 85.70%, 97.30%)",
		border: "hsl(240, 3.70%, 15.90%)",
		input: "hsl(240, 3.70%, 15.90%)",
		ring: "hsl(240, 4.90%, 83.90%)",
	},
};
