#!/usr/bin/env node

/**
 * This script generates a TypeScript file containing color variables
 * extracted from a global CSS file. It reads the CSS file, extracts
 * HSL color variables defined in the :root and .dark:root selectors,
 * and writes them to a TypeScript file in a structured format.
 */

const fs = require("fs");
const path = require("path");

// Paths
// eslint-disable-next-line no-undef
const globalCssPath = path.join(__dirname, "../global.css");
// eslint-disable-next-line no-undef
const colorsTsPath = path.join(__dirname, "../constants/colors.ts");

// Read global.css
if (!fs.existsSync(globalCssPath)) {
	console.error("Error: global.css file not found.");
	process.exit(1);
}

const cssContent = fs.readFileSync(globalCssPath, "utf-8");

// Extract HSL variables from both :root and .dark:root
const rootRegex = /:root\s*{([^}]*)}/;
const darkRootRegex = /\.dark:root\s*{([^}]*)}/;

// Helper function to convert kebab-case to camelCase
const toCamelCase = (str) =>
	str.replace(/-([a-z])/g, (_, char) => char.toUpperCase());

const extractColors = (cssBlock) => {
	const hslRegex = /--([\w-]+):\s*([\d.]+)\s+([\d.]+)%\s+([\d.]+)%;/g;
	const colors = {};
	let match;

	while ((match = hslRegex.exec(cssBlock)) !== null) {
		// eslint-disable-next-line no-unused-vars
		const [_, name, h, s, l] = match;
		colors[toCamelCase(name)] = `hsl(${h}, ${s}%, ${l}%)`;
	}

	return colors;
};

const rootMatch = rootRegex.exec(cssContent);
const darkRootMatch = darkRootRegex.exec(cssContent);

const rootColors = rootMatch ? extractColors(rootMatch[1]) : {};
const darkRootColors = darkRootMatch ? extractColors(darkRootMatch[1]) : {};

// Combine colors into a single object
const colors = {
	light: rootColors,
	dark: darkRootColors,
};

// Generate colors.ts content
const colorsTsContent = `/**
 * This file is auto-generated by the generate-colors.js script.
 * Do not edit this file directly.
 */

export const colors = ${JSON.stringify(colors, null, 2)};
`;

// Write to colors.ts
fs.writeFileSync(colorsTsPath, colorsTsContent, "utf-8");
console.log(`✅ colors.ts has been generated at ${colorsTsPath}`);
